/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tv_danmaku_ijk_media_publisher_LivePublisherJni */

#ifndef _Included_tv_danmaku_ijk_media_publisher_LivePublisherJni
#define _Included_tv_danmaku_ijk_media_publisher_LivePublisherJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tv_danmaku_ijk_media_publisher_LivePublisherJni
 * Method:    initRtmp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tv_danmaku_ijk_media_publisher_LivePublisherJni_initRtmp
  (JNIEnv *, jobject);

/*
 * Class:     tv_danmaku_ijk_media_publisher_LivePublisherJni
 * Method:    closeRtmp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tv_danmaku_ijk_media_publisher_LivePublisherJni_closeRtmp
  (JNIEnv *, jobject);

/*
 * Class:     tv_danmaku_ijk_media_publisher_LivePublisherJni
 * Method:    putAudioData
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_tv_danmaku_ijk_media_publisher_LivePublisherJni_putAudioData
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     tv_danmaku_ijk_media_publisher_LivePublisherJni
 * Method:    setCameraSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_tv_danmaku_ijk_media_publisher_LivePublisherJni_setCameraSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     tv_danmaku_ijk_media_publisher_LivePublisherJni
 * Method:    setCameraId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_tv_danmaku_ijk_media_publisher_LivePublisherJni_setCameraId
  (JNIEnv *, jobject, jint);

/*
 * Class:     tv_danmaku_ijk_media_publisher_LivePublisherJni
 * Method:    putVideoData
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_tv_danmaku_ijk_media_publisher_LivePublisherJni_putVideoData
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     tv_danmaku_ijk_media_publisher_LivePublisherJni
 * Method:    startAVPublisher
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tv_danmaku_ijk_media_publisher_LivePublisherJni_startAVPublisher
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
